apiVersion: telemetry.alibabacloud.com/v1alpha1
kind: ClusterAliyunPipelineConfig
metadata:
  name: fraud-detection-stdout
spec:
  project:
    name: your-sls-project
    endpoint: cn-hangzhou.log.aliyuncs.com
  logstores:
    - name: fraud-detection-logstore
  config:
    inputs:
      - Type: input_container_stdio
        IgnoringStdout: false
        IgnoringStderr: false
        ContainerFilters:
          IncludeK8sLabel:
            app: ^fraud-detection$
        K8sNamespaceRegex: ^default$
        ExternalK8sLabelTag:
          app: app
        ExternalEnvTag:
          SPRING_APPLICATION_NAME: spring_app_name
    processors:
      - Type: processor_parse_json_native
        SourceKey: content
        KeepingSourceWhenParseFail: true
        KeepingSourceWhenParseSucceed: false
    flushers:
      - Type: flusher_sls
        Logstore: fraud-detection-logstore
