FROM maven:3.9.9-eclipse-temurin-17 AS build
WORKDIR /workspace
COPY pom.xml .
COPY shared/pom.xml shared/pom.xml
COPY fraud-processor/pom.xml fraud-processor/pom.xml
COPY shared/src shared/src
COPY fraud-processor/src fraud-processor/src
RUN mvn -q -pl fraud-processor -am -DskipTests package

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /workspace/fraud-processor/target/fraud-processor-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
